# Generated by Django 5.1.5 on 2025-03-03 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_status_alter_category_options_category_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["title"], "verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="title",
        ),
    ]
