# Generated by Django 5.1.5 on 2025-03-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_contactessage_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactessage',
            new_name='ContactMessage',
        ),
    ]
